### PR TITLE
added mypy type hints

### LINKED ISSUE #21: add type hints
When using this library, mypy complains that the env_flag package doesn't have type hints or stubs.
```python
my_project.py:14: error: Skipping analyzing 'env_flag': found module but no type hints or library stubs
```

I believe you only need two type hints in the `env_flag` function, resulting in

```python
def env_flag(env_var: str, default=False) -> bool:
```

I am not 100% sure on this, but it's probably the only thing needed for this project to be correctly analyzed by mypy.

I didn't make a PR as it's probably much quicker for the owner to make this change instead of doing the fork-setup-edit-pr pipeline

### PR DESCRIPTION
**Pull request by HitLuca**
:building_construction: updated project to support mypy type annotations. Added __init__.pyi stub file and py.typed marker file. Updated setup.py to include new files
:memo: removed lint warnings from .md files

The project has been repackaged to allow introducing the new mypy type hint stubs

Closes #21

### CODE REVIEW

**Comment by paulmelnikow** [comment]
This looks good, thank you! I don't have whatever tool you're using to format the markdown, so would you mind resetting those?

**Comment by HitLuca** [comment]
I just removed some empty spaces to be compliant, nothing fancy.
to test the new stubs, create a new project and install env_flag and mypy. Add a Python file that imports your function and then try to run mypy your_file.py. It should give you an error.
then try to build and install the updated version, go through the same process and the error should disappear

**Comment by paulmelnikow** [comment]
Can confirm it works! Thanks for the PR!

**Comment by paulmelnikow** [comment]
@HitLuca I installed the pyi plugin for the linter and it complained about too many statements per line in the pyi file. To make it happy I moved the types into the source code. It still seems to be working for me in a descendant project. Want to give it a try yourself to make sure?

**Comment by HitLuca** [comment]
can confirm it works

**Pull request merged**
